# Using Merger trees

In [ ]:
import h5py
import pandas as pd
import numpy as np
samples = pd.read_csv('../data/samples_in_lightcone0.csv')
catalog = pd.read_hdf('../data/halo_properties_in_lightcone0.hdf5')
vr_tree = h5py.File('/data2/FLAMINGO/L1000N1800/HYDRO_FIDUCIAL/merger_trees/vr_trees.hdf5', 'r')

In [ ]:
# Matching soap catalogue with merger tree ids!
samples['GalaxyID'] = -1
samples['TopLeafID'] = -1
for i in range(len(samples)):
    snap_num = samples.loc[i, 'snap_num']
    soapid = samples.loc[i, 'SOAPID']
    galaxyid = vr_tree['SOAP/Snapshot00'+str(snap_num)][soapid]
    
    samples.loc[i, 'GalaxyID'] = galaxyid
    samples.loc[i, 'TopLeafID'] = vr_tree['MergerTree/TopLeafID'][galaxyid]

# I doubt it's needed to account for progenitors and descendants,
# because the dynamics is different after mergers.

In [ ]:
dup_mask = (np.abs(samples['x_lc']) > 500) | (np.abs(samples['y_lc']) > 500) | (np.abs(samples['z_lc']) > 500)
samples_dup = samples[dup_mask]
samples_near = samples[~dup_mask]

In [ ]:
len(samples_dup)

69

In [ ]:
# 1 Find samples_dup's near universe counterparts
# Not founded for whatever reason
mergerids = samples_dup['GalaxyID']
near_mergerids = vr_tree['SOAP/Snapshot0075'][:]
print(np.sum(np.isin(mergerids, near_mergerids))) # >>
print(np.sum(np.isin(near_mergerids, mergerids))) # >>

0
0


In [ ]:
# 2 Find them from same topleaf
topleafids = samples_dup['TopLeafID']
near_mergerids = vr_tree['SOAP/Snapshot0075'][:]
near_topleafids = vr_tree['MergerTree/TopLeafID'][:][near_mergerids]
print(np.sum(np.isin(topleafids, near_topleafids))) # >> 65
print(np.sum(np.isin(near_topleafids, topleafids))) # >> 58 multiple duplicates -> one near universe counterpart!
# >> 65 out of 69! Not bad

68
61


In [ ]:
np.sum(np.isin(samples_dup['TopLeafID'], samples_near['TopLeafID']))

49

In [ ]:
np.intersect1d(samples_dup['TopLeafID'], samples_near['TopLeafID'])

array([ 46076833,  46647332, 161039594, 167877905, 170714420, 171851690,
       184580684, 187230211, 282510918, 334103242, 343189958, 345110682,
       357334365, 397671033, 404772937, 457996413, 528526380, 536568968,
       562645652, 566327479, 578365166, 604531732, 623713826, 640990623,
       647147338, 650252744, 712023421, 716546697, 724578024, 743711202,
       785494899, 787706529, 810814802, 826368038, 839275696, 858854857,
       863550888, 863835432, 893661109, 901789918, 902646262, 904230047])

In [ ]:
771-len(samples.drop_duplicates(subset=['TopLeafID'])) # This means all 49 clusters are between near and far universes

49

Find from which snapshot and which halo in the near universe counterpart!

In [ ]:
# Matching soap catalogue with merger tree ids!
catalog['GalaxyID'] = -1
catalog['TopLeafID'] = -1
for i in range(len(catalog)):
    snap_num = catalog.loc[i, 'snap_num']
    soapid = catalog.loc[i, 'SOAPID']
    galaxyid = vr_tree['SOAP/Snapshot00'+str(snap_num)][soapid]
    
    catalog.loc[i, 'GalaxyID'] = galaxyid
    catalog.loc[i, 'TopLeafID'] = vr_tree['MergerTree/TopLeafID'][galaxyid]

In [ ]:
dup_df = samples_dup.merge(catalog, on=['TopLeafID', 'snap_num'], how='inner')

Ones that are found in snapshot0077 but didn't make it into the cut (65-49=16)

In [ ]:
# get the topleafids of the 16
mask = np.isin(samples_dup['TopLeafID'], near_topleafids)
abnormal_dup = samples_dup[mask]
mask = np.isin(abnormal_dup['TopLeafID'], samples_near['TopLeafID'])
abnormal_dup = abnormal_dup[~mask]
abnormal_dup.sort_values(by='TopLeafID') # Sort by topleafid so that the final list of near universe counterparts is matched in this order for easy comparison
n = len(abnormal_dup)
print(len(abnormal_dup))

# Find which near universe's topleafids match the 16's
match = np.isin(near_topleafids, abnormal_dup['TopLeafID'])
print(np.sum(match))

# match the 16's topleafids to near universe's galaxyids
match_galaxyids = near_mergerids[match]
assert len(match_galaxyids) == n
soapids = np.array([])
for i in range(len(match_galaxyids)):
    soapids = np.concatenate((soapids, np.where(vr_tree['SOAP/Snapshot0077'][:] == match_galaxyids[i])[0]))
print(soapids)

16
16
[  920389.  1874057.  2600905.  2706639.  4556268.  5329332.  5668871.
  5772921.  5858678.  6560748.  9097199.  9430379. 10712266. 11897190.
 12587038. 13016203.]


In [ ]:
np.argwhere(np.array([1,2,3,4,5])==5)[0]

array([4])

In [ ]:
catalog['SOAPID']

In [ ]:
np.isin(np.array(soapids), catalog['SOAPID'])

array([ True, False, False, False, False, False, False, False, False,
        True, False, False, False, False,  True, False])

In [ ]:
catalog.loc[catalog['snap_num'] == 77]

lc_id  redshift  theta_on_lc  phi_on_lc      M_fof_lc       x_lc  \
1589230  13017956  0.021017     1.030311  43.908471  8.583189e+12  66.329352   
1589231  13017333  0.021250     6.911810  47.844790  1.447236e+13  61.859496   
1589232  13018171  0.024445     4.466595  43.329278  8.589794e+12  77.667462   
1589233  13017776  0.022881    12.008518  50.984997  9.003344e+12  61.698615   
1589234  13017602  0.022794    13.092200  52.013974  1.071530e+13  59.841805   
...           ...       ...          ...        ...           ...        ...   
1591021  11899510  0.022797    -5.885697 -46.840753  5.021522e+12  67.926424   
1591022  11897458  0.013024    -2.161575 -46.702473  4.378664e+13  39.037703   
1591023  11899156  0.012694    -4.197473 -49.181849  6.492990e+12  36.322263   
1591024  11897740  0.022186    -1.912917 -47.332148  2.287207e+13  65.799154   
1591025  11898341  0.015292    -2.203340 -46.538524  1.272166e+13  46.120053   

              y_lc       z_lc  snap_num      MfofSOAP  ...          M500  \
1589230  63.849052   1.655752        77  8.581345e+12  ...  5.866925e+12   
1589231  68.328786  11.173146        77  1.446545e+13  ...  8.693014e+12   
1589232  73.265082   8.340412        77  8.589935e+12  ...  4.269198e+12   
1589233  76.150665  20.847555        77  9.002251e+12  ...  6.597070e+12   
1589234  76.632535  22.612075        77  1.072024e+13  ...  5.841156e+12   
...            ...        ...       ...           ...  ...           ...   
1591021 -72.437476 -10.236966        77  5.025112e+12  ...  2.778844e+12   
1591022 -41.429387  -2.148567        77  4.377431e+13  ...  2.642264e+13   
1591023 -42.052807  -4.078157        77  6.493991e+12  ...  3.534758e+12   
1591024 -71.386186  -3.242556        77  2.288359e+13  ...  1.565086e+13   
1591025 -48.665887  -2.579637        77  1.271310e+13  ...  7.121056e+12   

              GasMass  LX0InRestframeWithoutRecentAGNHeating  \
1589230  6.100196e+10                           7.001310e+40   
1589231  1.683090e+11                           2.769898e+41   
1589232  5.207648e+10                           2.879640e+40   
1589233  2.248147e+10                           1.242031e+40   
1589234  7.730941e+10                           3.526176e+40   
...               ...                                    ...   
1591021  5.650566e+10                           2.360709e+40   
1591022  1.142461e+12                           1.736801e+42   
1591023  5.408974e+10                           3.045527e+40   
1591024  6.055904e+11                           6.227167e+41   
1591025  1.199906e+11                           9.289709e+40   

         LX0InRestframeWithoutRecentAGNHeatingCoreExcision  \
1589230                                       2.241610e+40   
1589231                                       2.769898e+41   
1589232                                       1.439820e+40   
1589233                                       1.924722e+39   
1589234                                       2.356455e+40   
...                                                    ...   
1591021                                       2.360709e+40   
1591022                                       1.377463e+42   
1591023                                       3.045527e+40   
1591024                                       4.614229e+41   
1591025                                       9.289709e+40   

         GasTemperatureWithoutRecentAGNHeatingCoreExcision  \
1589230                                          2813952.0   
1589231                                          3518464.0   
1589232                                          1742848.0   
1589233                                         13008896.0   
1589234                                          4874240.0   
...                                                    ...   
1591021                                           295936.0   
1591022                                          9502720.0   
1591023                                          2441216.0   
1591

## output from 7duplicate_match.py


1. The 9 halos that are first observed and not duplicated in near universe

In [1]:
import pandas as pd
import numpy as np
import h5py
unmatched_dup = pd.read_csv('../data/unmatched_duplicates.csv')
catalog = pd.read_csv('../data/halo_properties_in_lightcone0_with_tree.csv')
vr_tree = h5py.File('/data2/FLAMINGO/L1000N1800/HYDRO_FIDUCIAL/merger_trees/vr_trees.hdf5', 'r')

In [8]:
# Are there duplicates throughout the catalog? 
match = pd.merge(unmatched_dup, catalog, on=['TopLeafID'], how='inner')

In [13]:
for snap_num in range(72, 77+1):
    topleafids = unmatched_dup['TopLeafID']
    near_mergerids = vr_tree['SOAP/Snapshot00'+str(snap_num)][:]
    near_topleafids = vr_tree['MergerTree/TopLeafID'][:][near_mergerids]
    n_matched = np.sum(np.isin(topleafids, near_topleafids))
    print(n_matched) # >> 65
    assert np.sum(np.isin(near_topleafids, topleafids)) == n_matched # one-to-one match
    for i in range(len(topleafids)):
        topleafid = topleafids[i]
        soapidx = np.argwhere(near_topleafids == topleafid)
        if len(soapidx) > 0:
            unmatched_dup.loc[unmatched_dup['TopLeafID']==topleafid, 'SOAPID_near'] = soapidx[0][0]
            unmatched_dup.loc[unmatched_dup['TopLeafID']==topleafid, 'snap_num_near'] = snap_num
        
        print(snap_num, soapidx, topleafid)

9
72 [[5644094]] 377700723
72 [[4988097]] 419587918
72 [[6301647]] 412589
72 [[2678353]] 123454236
72 [[11390513]] 534273563
72 [[2888993]] 567251456
72 [[9897687]] 680357185
72 [[6301511]] 270568914
72 [[6199227]] 671949215
8
73 [[5564836]] 377700723
73 [[4917583]] 419587918
73 [[6212701]] 412589
73 [[2641832]] 123454236
73 [[11234915]] 534273563
73 [[2756095]] 567251456
73 [] 680357185
73 [[6212795]] 270568914
73 [[6112399]] 671949215
8
74 [[5487083]] 377700723
74 [[4762169]] 419587918
74 [[6035409]] 412589
74 [[2605336]] 123454236
74 [[10987595]] 534273563
74 [[2718119]] 567251456
74 [] 680357185
74 [[6035410]] 270568914
74 [[5928187]] 671949215
8
75 [[5492818]] 377700723
75 [[4779176]] 419587918
75 [[6038154]] 412589
75 [[2660208]] 123454236
75 [[10917194]] 534273563
75 [[2769935]] 567251456
75 [] 680357185
75 [[6038261]] 270568914
75 [[5940819]] 671949215
6
76 [[5413399]] 377700723
76 [[4627880]] 419587918
76 [[5863617]] 412589
76 [[2622487]] 123454236
76 [] 534273563
76 [[2642411

In [23]:
# Extract their soap id and snapshot number
soap = h5py.File('/data2/FLAMINGO/L1000N1800/HYDRO_FIDUCIAL/SOAP/halo_properties_00'+str(snap_num)+'.hdf5', 'r')
soap['FOFSubhaloProperties/CentreOfMass'][5858678]

array([575.47369276, 615.74286276, 347.50427276])

In [24]:
soap['FOFSubhaloProperties/CentreOfMass'][2600905]

array([745.48107876,  82.16690876, 388.35622876])

2. The 11 clusters that was observed a 2nd time but did not make the sample selection

In [1]:
import pandas as pd
import numpy as np
import h5py
matched_dup = pd.read_csv('../data/matched_duplicates.csv')
catalog = pd.read_hdf('../data/halo_properties_in_lightcone0_with_tree.hdf5', key='catalog')
samples = pd.read_csv('../data/samples_in_lightcone0_with_tree.csv')

In [2]:
box_mask = (np.abs(samples['x_lc']) <= 500) | (np.abs(samples['y_lc']) <= 500) | (np.abs(samples['z_lc']) <= 500)
cut = np.isin(matched_dup['GalaxyID_near'], samples['GalaxyID'][box_mask]) # mask nearby universe counterparts that make the cut
cutted_near_dup_info = matched_dup[~cut] # select those that didn't make the cut
print(len(cutted_near_dup_info)) # should be 11
cutted_near_dup_info.reset_index(drop=True, inplace=True) # reset index for easy iteration

box_mask = (np.abs(catalog['x_lc']) <= 500) | (np.abs(catalog['y_lc']) <= 500) | (np.abs(catalog['z_lc']) <= 500)
catalog_near = catalog[box_mask] # consider only the near field duplicates

cutted_near_dup_properties = pd.DataFrame()
for i in range(len(cutted_near_dup_info)):
    soapidx = cutted_near_dup_info.loc[i, 'SOAPID_near']
    snap_num = cutted_near_dup_info.loc[i, 'snap_num_near']
    cutted_near_dup_property = catalog_near.loc[(catalog_near['SOAPID'] == soapidx) & (catalog_near['snap_num'] == snap_num)]
    cutted_near_dup_properties = pd.concat([cutted_near_dup_properties, cutted_near_dup_property])

11


In [3]:
cutted_near_dup_properties.reset_index(drop=True, inplace=True)
cutted_near_dup_properties

lc_id  redshift  theta_on_lc   phi_on_lc      M_fof_lc        x_lc  \
0    5842388  0.115570    55.950588   47.940239  1.200677e+14  185.731693   
1    9714207  0.094224    26.902743   63.470385  1.719874e+14  161.601974   
2    1958771  0.143625    33.405415   76.711787  6.569873e+14  117.214133   
3    1958771  0.145055    33.036706  -76.901846  6.569873e+14  117.196817   
4   12080849  0.041231   -16.160838  -80.415476  4.788929e+14   28.747816   
5    2828679  0.173707    47.953336   86.923047  4.460436e+14   26.362356   
6    2828679  0.158041   -42.823858   86.907184  4.460436e+14   26.506541   
7    2828679  0.161488   -41.753623  -87.026898  4.460436e+14   26.461372   
8    9371747  0.101100    15.175875  122.139541  1.653275e+15 -223.151321   
9    6860788  0.147553   -19.572528   52.093439  1.686950e+15  362.995047   
10   6860788  0.160274   -18.023058  -55.796112  1.686950e+15  362.917060   
11  11037071  0.085311     3.000397  -36.135107  2.156607e+15  297.382166   
12  12782338  0.042194     1.300753  -59.773301  1.985666e+15   91.895481   
13    963218  0.172488   -30.069626   41.270770  8.341149e+14  473.976605   
14  13217915  0.054207    13.680244    6.366789  1.762473e+15  227.319492   

          y_lc        z_lc  snap_num      MfofSOAP  ...  \
0   205.843771  410.277310        75  1.201216e+14  ...   
1   323.704308  183.573702        75  1.720736e+14  ...   
2   496.306707  336.326016        74  6.575080e+14  ...   
3  -503.696830  336.313290        74  6.575080e+14  ...   
4  -170.246934  -50.033560        76  4.788373e+14  ...   
5   490.420091  544.560475        74  4.458520e+14  ...   
6   490.568316 -455.314020        74  4.458520e+14  ...   
7  -509.489293 -455.407440        74  4.458520e+14  ...   
8   355.188931  113.778035        75  1.653666e+15  ...   
9   466.177523 -210.067995        74  1.686651e+15  ...   
10 -533.938294 -210.055322        74  1.686651e+15  ...   
11 -217.134042   19.299964        75  2.157242e+15  ...   
12 -157.723146    4.144846        76  1.985718e+15  ...   
13  415.970380 -365.112765        74  8.345293e+14  ...   
14   25.364551   55.674870        76  1.761418e+15  ...   

    LX0InRestframeWithoutRecentAGNHeating  \
0                            9.495239e+42   
1                            3.197021e+43   
2                            3.156949e+44   
3                            3.156949e+44   
4                            7.491657e+43   
5                            1.864203e+44   
6                            1.864203e+44   
7                            1.864203e+44   
8                            8.989988e+44   
9                            1.179152e+45   
10                           1.179152e+45   
11                           1.002140e+45   
12                           1.000746e+45   
13                           4.920102e+44   
14                           5.456714e+44   

    LX0InRestframeWithoutRecentAGNHeatingCoreExcision  \
0                                        7.611436e+42   
1                                        2.478345e+43   
2                                        2.526256e+44   
3                                        2.526256e+44   
4                                        6.489865e+43   
5                                        1.641195e+44   
6                                        1.641195e+44   
7                                        1.641195e+44   
8                                        6.286023e+44   
9                                        1.023047e+45   
10                                       1.023047e+45   
11                                       8.613663e+44   
12                                       7.763447e+44   
13                                       4.160483e+44   
14                                       4.585591e+44   

    GasTemperatureWithoutRecentAGNHeatingCoreExcision  \
0                                          16629760.0   
1                                          20709376.0   
2                       

In [4]:
cutted_near_dup_properties['SpectroscopicLikeTemperatureWithoutRecentAGNHeatingCoreExcision'] /= 11605425

In [5]:
pd.set_option('display.max_columns', None)
cutted_near_dup_properties.loc[np.abs(cutted_near_dup_properties['theta_on_lc'])>20]

lc_id  redshift  theta_on_lc  phi_on_lc      M_fof_lc        x_lc  \
0   5842388  0.115570    55.950588  47.940239  1.200677e+14  185.731693   
1   9714207  0.094224    26.902743  63.470385  1.719874e+14  161.601974   
2   1958771  0.143625    33.405415  76.711787  6.569873e+14  117.214133   
3   1958771  0.145055    33.036706 -76.901846  6.569873e+14  117.196817   
5   2828679  0.173707    47.953336  86.923047  4.460436e+14   26.362356   
6   2828679  0.158041   -42.823858  86.907184  4.460436e+14   26.506541   
7   2828679  0.161488   -41.753623 -87.026898  4.460436e+14   26.461372   
13   963218  0.172488   -30.069626  41.270770  8.341149e+14  473.976605   

          y_lc        z_lc  snap_num      MfofSOAP   SOAPID          M500  \
0   205.843771  410.277310        75  1.201216e+14  5842387  6.040442e+13   
1   323.704308  183.573702        75  1.720736e+14  9714206  9.400824e+13   
2   496.306707  336.326016        74  6.575080e+14  1958770  3.919759e+14   
3  -503.696830  336.313290        74  6.575080e+14  1958770  3.919759e+14   
5   490.420091  544.560475        74  4.458520e+14  2828678  3.067637e+14   
6   490.568316 -455.314020        74  4.458520e+14  2828678  3.067637e+14   
7  -509.489293 -455.407440        74  4.458520e+14  2828678  3.067637e+14   
13  415.970380 -365.112765        74  8.345293e+14   963217  6.146270e+14   

         GasMass  LX0InRestframeWithoutRecentAGNHeating  \
0   3.839701e+12                           9.495239e+42   
1   8.332237e+12                           3.197021e+43   
2   4.617949e+13                           3.156949e+44   
3   4.617949e+13                           3.156949e+44   
5   3.463462e+13                           1.864203e+44   
6   3.463462e+13                           1.864203e+44   
7   3.463462e+13                           1.864203e+44   
13  7.559142e+13                           4.920102e+44   

    LX0InRestframeWithoutRecentAGNHeatingCoreExcision  \
0                                        7.611436e+42   
1                                        2.478345e+43   
2                                        2.526256e+44   
3                                        2.526256e+44   
5                                        1.641195e+44   
6                                        1.641195e+44   
7                                        1.641195e+44   
13                                       4.160483e+44   

    GasTemperatureWithoutRecentAGNHeatingCoreExcision  \
0                                          16629760.0   
1                                          20709376.0   
2                                          50200576.0   
3                                          50200576.0   
5                                          39845890.0   
6                                          39845890.0   
7                                          39845890.0   
13                                         60293120.0   

    SpectroscopicLikeTemperatureWithoutRecentAGNHeatingCoreExcision  \
0                                            1.476694                 
1                                            1.965161                 
2                                            4.783021                 
3                                            4.783021                 
5                                            3.501149                 
6                                            3.501149                 
7                                            3.501149                 
13                                           5.104901                 

    Y5R500WithoutRecentAGNHeating          Vx         Vy          Vz  \
0                    2.678703e+43  286.602360  196.10236  137.902400   
1                    5.174470e+43  -84.353330  147.04663 -210.353330   
2                    5.303396e+44  -57.684387 -248.18439  226.315610   
3                    5.303396e+44  -57.684387 -248.18439  226.315610   
5                    2.933942e+44  329.610600 -146.08942 -491.089420   
6   

In [6]:
from unyt import Mpc, cm
r = (cutted_near_dup_properties['x_lc']**2 + cutted_near_dup_properties['y_lc']**2 + cutted_near_dup_properties['z_lc']**2)**0.5
r = (np.array(r)*Mpc).to(cm)
z = cutted_near_dup_properties['redshift']
z = np.array(z)

c = 299792.458                  # the speed of light in km/s

vx = cutted_near_dup_properties['Vx']                 # velocities in km/s
vy = cutted_near_dup_properties['Vy']
vz = cutted_near_dup_properties['Vz']

rx = cutted_near_dup_properties['x_lc']
ry = cutted_near_dup_properties['y_lc']
rz = cutted_near_dup_properties['z_lc']

los_v = (vx*rx + vy*ry + vz*rz) / (rx**2 + ry**2 + rz**2)**0.5
beta = los_v / c
z_pec = (1 + los_v/c) / (1 - beta**2)**0.5 - 1
z_obs = (z + 1) * (z_pec + 1) - 1
z_obs = np.array(z_obs)

r = r * (1 + z_obs)

cutted_near_dup_properties['LX0InRestframeWithoutRecentAGNHeating']/(1+z)**3 / r**2 / 4 / np.pi

0     1.869472e-13
1     1.034927e-12
2     3.616440e-12
3     3.514778e-12
4     1.585546e-11
5     1.304685e-12
6     1.664714e-12
7     1.571319e-12
8     2.462275e-11
9     1.258538e-11
10    1.013800e-11
11    4.091242e-11
12    2.039077e-10
13    3.494519e-12
14    6.326545e-11
Name: LX0InRestframeWithoutRecentAGNHeating, dtype: float64

# Summary
- 69 out of 771 lies outside of one box size and should be duplicates
- None is labeled the same cluster by the merger tree
- 49 out of 69 have the same progenitors with some near universe clusters in our sample
- 11 out of 69 have near universe counterparts that was in lightcone but did not make the cut.
     11 matched 15 near universe duplicates, 7 of which are cut out by galactic latitude, and 8 by flux.
     One cluster in particular becomes dimmer (in LX) by 100 times by 0.1 redshift
- 9 out of 69 have near universe counterparts in soap catalogue but did not get into the lightcone earlier, i.e. they are not duplicated. This is the first time they are observed.
