In [1]:
import h5py
from astropy.cosmology import FlatLambdaCDM
cosmo = FlatLambdaCDM(H0=68.1, Om0=0.306)

def is_light_like(z, r, cosmo):
    """
    Tell if an object at a comoving coordinate is observable at given redshift.
    Output false if the spacetime interval is space-like and true if light-like.  

    light-like = (cdt/a(t))^2 > (dr)^2
    space-like = (cdt/a(t))^2 < (dr)^2
    """
    flags = (cosmo.comoving_distance(z) > r)  # Bool or a list of bool

    return flags


In [3]:
f = h5py.File('../data/halo_properties_0001.hdf5', 'r')

In [6]:
list(f.keys())

['BoundSubhaloProperties',
 'ExclusiveSphere',
 'FOFSubhaloProperties',
 'InclusiveSphere',
 'Parameters',
 'ProjectedAperture',
 'RecentlyHeatedGasFilter',
 'SO',
 'SOAP',
 'SWIFT',
 'SearchRadius',
 'VR']

In [11]:
import numpy as np
np.arange(10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [16]:
(-501+500)%1000 - 500

499

In [17]:
np.full(5, 6)

array([6, 6, 6, 6, 6])

In [25]:
from astropy.cosmology import FlatLambdaCDM
cosmo = FlatLambdaCDM(H0=68.1, Om0=0.306)

# Solve when comoving distance is 0.5 Mpc
import scipy.optimize as opt
z = opt.newton(lambda z: cosmo.comoving_distance(z=z).value - np.array([500, 1000]), [0.1,0.1])
z

array([0.11677295, 0.24095309])

In [26]:
cosmo.comoving_distance(z=z)

<Quantity [ 500., 1000.] Mpc>