In [8]:
import sys
sys.path.append('../tools')
import clusterfit as cf
print(cf.angular_separation(128, -16, 80, 30))
print(cf.angular_separation(-56, 66, -68, 20))

65.21482444607726
46.66157916962223


In [68]:
from scipy.integrate import quad
import numpy as np
n=5.4
s=1 # Set as any number, doesn't matter
p = quad(lambda x: 1/np.sqrt(2*np.pi*s**2) * np.e**(-x**2/(s**2)/2), -n*s, n*s)[0]
p = 1 - p # The p(x>n*s) n sigma probability of a normal distribution
print(1-p) 

0.9999999333591032


In [47]:
# The probability of at least one event x>n*s for m events
m=50
1 - (1-p)**m

0.37393749700020007

In [62]:
from astropy.cosmology import FlatLambdaCDM
cosmo = FlatLambdaCDM(H0=68.1, Om0=0.306)
vol0 = 0
for z in [0.06, 0.08, 0.10, 0.12]:
    print(cosmo.comoving_distance(z))
    
    vol1 = 4/3*np.pi*cosmo.comoving_distance(z)**3
    if vol0 == 0:
        vol0 = vol1
    
    print(f'{(vol1 - vol0) / vol0:.2%}')

    vol0 = vol1

    # print(, '\n')

260.455252760345 Mpc
0.00%
345.6163267566517 Mpc
133.66%
429.9369053174122 Mpc
92.50%
513.4113459687144 Mpc
70.29%


In [71]:
import numpy as np
n_cone = 6
idx = np.random.choice(10, size=n_cone, replace=True)
print(idx)

[4 1 4 6 8 7]


In [1]:
1000 / 3e5

0.0033333333333333335

In [1]:
900/3e5

0.003

In [1]:
import pandas as pd
data = pd.read_csv('../data/samples_in_lightcone0_with_trees_duplicate_excision_outlier_excision.csv')
data

lc_id  redshift  theta_on_lc   phi_on_lc      M_fof_lc        x_lc  \
0    12678101  0.049663    68.444418 -146.100556  3.221621e+14  -65.892905   
1    13217952  0.031250    61.242576   66.517408  2.121565e+14   26.197568   
2    11897316  0.016130   -50.768598  -21.506782  9.199489e+13   41.950287   
3    12785470  0.019369    28.752838  151.820271  1.019505e+14  -65.416111   
4     6057316  0.077597   -74.324178 -132.555680  2.872746e+14  -61.330249   
..        ...       ...          ...         ...           ...         ...   
701  11804705  0.085544    22.449321  158.121013  5.532838e+14 -316.531368   
702  11861703  0.028225   -55.011456 -126.277785  7.538000e+13  -41.823558   
703   4646616  0.125712   -33.564085 -169.939991  8.079670e+14 -442.983802   
704  12882763  0.052263    43.009397  -35.045370  1.727982e+14  135.647971   
705  11897198  0.016366   -33.124879  -28.281435  3.261190e+14   53.345272   

           y_lc        z_lc  snap_num      MfofSOAP  ...  \
0    -44.277266  200.964592        76  3.221569e+14  ...   
1     60.300376  119.801093        76  2.122057e+14  ...   
2    -16.530393  -55.223603        77  9.194666e+13  ...   
3     35.046019   40.719139        77  1.019797e+14  ...   
4    -66.799779 -323.142433        75  2.875223e+14  ...   
..          ...         ...       ...           ...  ...   
701  127.109968  140.934807        75  5.530544e+14  ...   
702  -56.982167 -100.989675        76  7.531655e+13  ...   
703  -78.588470 -298.507096        74  8.081410e+14  ...   
704  -95.141897  154.556921        76  1.728982e+14  ...   
705  -28.701178  -39.526618        77  3.260052e+14  ...   

     Y5R500WithoutRecentAGNHeating         Vx          Vy          Vz  \
0                        13.394281 -138.41480  146.285160 -258.814820   
1                         8.353127  136.95007   85.050050  156.950070   
2                         1.736042 -143.69714 -196.297180  -29.697144   
3                         2.198071 -126.92236  256.877560    1.177612   
4                        12.424476  168.31421   95.214230   99.214230   
..                             ...        ...         ...         ...   
701                      77.584358  492.35680  242.556760   50.656740   
702                       2.511428   98.96692 -309.533080 -453.733030   
703                     140.383773 -671.88740   77.012570 -361.787350   
704                      10.978919 -296.42468  159.875300  135.375300   
705                      27.483893  143.50280   39.602783  100.902830   

      GalaxyID  TopLeafID  3DLcore/Ltot  ObservedRedshift          Flux  \
0    264729502  264729571      0.629913          0.048863  1.930583e-11   
1    758729120  758729192      0.563404          0.031943  3.424318e-11   
2    735257909  735257982      0.587601          0.016076  1.415207e-11   
3    553518674  553518749      0.448886          0.020066  1.010312e-11   
4    256178182  256178252      0.538358          0.077076  7.649637e-12   
..         ...        ...           ...               ...           ...   
701  795913407  795913476      0.020071          0.084388  2.813252e-11   
702  261040288  261040362      0.020155          0.029877  7.749973e-12   
703  690964560  690964632      0.002155          0.128495  6.101368e-12   
704  583385361  583385430      0.011669          0.051729  5.409843e-12   
705   30776977   30777043      0.001408          0.016484  1.030848e-10   

     2DLcore/Ltot  
0        0.655002  
1        0.619050  
2        0.580910  
3        0.540358  
4        0.485846  
..            ...  
701      0.060460  
702      0.057530  
703      0.047056  
704      0.042653  
705      0.011050  

[706 rows x 29 columns]

In [3]:
twod = data[:313]
data.sort_values('3DLcore/Ltot', ascending=False, inplace=True)
thrd = data[:313]

In [5]:
import numpy as np
np.sum(np.isin(twod.index, thrd.index))

277

In [9]:
v = (data['Vx']**2 + data['Vy']**2 + data['Vz']**2)**0.5

In [10]:
import numpy as np
np.max(v)

1335.7033971067572

In [3]:
data['redshift'].min()

0.0040453672

In [19]:
1335/299792.458

0.0044530806708953305

In [20]:
((1+1335/299792.458) / (1-1335/299792.458))**0.5 - 1

0.004463039934878399

In [21]:
(0.00463 - 0.00453) / 0.00453

0.022075055187637836

In [6]:
0.99**1000

4.317124741065786e-05

In [5]:
from astropy.cosmology import FlatLambdaCDM
cosmo = FlatLambdaCDM(H0=68.1, Om0=0.306)
cosmo.comoving_distance(z=[0.12, 0.35])

<Quantity [ 513.41134597, 1411.76563403] Mpc>

In [68]:
print(f'{55:04d}')

0055


In [62]:
import pandas as pd
import h5py
import numpy as np
with h5py.File('./test.hdf5', mode='a') as f:
    f.visit(print)
    #f.create_dataset('lightcone0/id', data=np.arange(5))
    #f.create_group('lightcone1')
    print(f['lightcone0/id'][:][[True, False, True, False, True]])
    f['lightcone1'].attrs['loc']=[1.5,1.5,1.5]
    print(f['lightcone1'].attrs['loc'])
    


lightcone0
lightcone0/id
lightcone1
[0 2 4]
[1.5 1.5 1.5]


In [18]:
pd.read_hdf('./test.hdf5')

one  two
0    1    2
1    2    3